# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MessengerService

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8da7b42cb5504a5e83727107f53e01df }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bb3764e3a6ba43ac9bd4123ed1aa51e7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8da7b42cb5504a5e83727107f53e01df }}/braslyn/messengerservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MessengerService'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce95848c5e274ab2b19640740b22f8a3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8da7b42cb5504a5e83727107f53e01df }}/braslyn/messengerservice:${{ github.sha }}'