name: Go

on:
  push:
    branches: [ "develop", "dev" ]
  pull_request:
    branches: [ "develop", "dev" ]
  schedule:
  - cron: "0 2 * * 1-5"
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: | 
        cd Endpoint\main
        go build -v
        cd ..\.. 

    - name: Test
      run: go test MessengerService/...
